---
title: "git_00"
author: "Sandra Iovino "
date: "Summer 2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

Twas brillig, and the slithy toves

      Did gyre and gimble in the wabe:  
All mimsy were the borogoves,  
      And the mome raths outgrabe. 
      
“Beware the Jabberwock, my son!  
      The jaws that bite, the claws that catch!  
Beware the Jubjub bird, and shun
      The frumious Bandersnatch!”  
      
      
## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

Then took the other, as just as fair,  
And having perhaps the better claim,  
Because it was grassy and wanted wear;  
Though as for that the passing there  
Had worn them really about the same,  

And both that morning equally lay  
In leaves no step had trodden black.  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

"The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make  
      The billows smooth and bright —  
And this was odd, because it was  
      The middle of the night.  
 
The moon was shining sulkily,  
      Because she thought the sun  
Had got no business to be there  
      After the day was done —  
"It's very rude of him," she said,  
      "To come and spoil the fun."  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

And the Raven, never flitting,  
Still is sitting, still is sitting  
On the pallid bust of Pallas  
Just above my chamber door;  
And his eyes have all the seeming  
Of a demon's that is dreaming,  
And the lamplight o'er him streaming  
Throws his shadow on the floor;  
And my soul from out that shadow  
That lies floating on the floor
  Shall be lifted—nevermore!   